"""Hershey Simplex font codes from https://paulbourke.net/dataformats/hershey/

This is a vector font that's good for G-code.
"""

_lowercase_data = r"""
  601 18I\XMX[ RXPVNTMQMONMPLSLUMXOZQ[T[VZXX
  602 18H[LFL[ RLPNNPMSMUNWPXSXUWXUZS[P[NZLX
  603 15I[XPVNTMQMONMPLSLUMXOZQ[T[VZXX
  604 18I\XFX[ RXPVNTMQMONMPLSLUMXOZQ[T[VZXX
  605 18I[LSXSXQWOVNTMQMONMPLSLUMXOZQ[T[VZXX
  606  9MYWFUFSGRJR[ ROMVM
  607 23I\XMX]W`VaTbQbOa RXPVNTMQMONMPLSLUMXOZQ[T[VZXX
  608 11I\MFM[ RMQPNRMUMWNXQX[
  609  9NVQFRGSFREQF RRMR[
  610 12MWRFSGTFSERF RSMS^RaPbNb
  611  9IZMFM[ RWMMW RQSX[
  612  3NVRFR[
  613 19CaGMG[ RGQJNLMOMQNRQR[ RRQUNWMZM\N]Q][
  614 11I\MMM[ RMQPNRMUMWNXQX[
  615 18I\QMONMPLSLUMXOZQ[T[VZXXYUYSXPVNTMQM
  616 18H[LMLb RLPNNPMSMUNWPXSXUWXUZS[P[NZLX
  617 18I\XMXb RXPVNTMQMONMPLSLUMXOZQ[T[VZXX
  618  9KXOMO[ ROSPPRNTMWM
  619 18J[XPWNTMQMNNMPNRPSUTWUXWXXWZT[Q[NZMX
  620  9MYRFRWSZU[W[ ROMVM
  621 11I\MMMWNZP[S[UZXW RXMX[
  622  6JZLMR[ RXMR[
  623 12G]JMN[ RRMN[ RRMV[ RZMV[
  624  6J[MMX[ RXMM[
  625 10JZLMR[ RXMR[P_NaLbKb
  626  9J[XMM[ RMMXM RM[X[
""".strip('\n')
_lowercase_chars = [chr(x) for x in range(ord('a'), ord('z') + 1)]
_lowercase_dict = dict(zip(_lowercase_chars, [line[6:] for line in _lowercase_data.split('\n')]))

_uppercase_data = r"""
  501  9I[RFJ[ RRFZ[ RMTWT
  502 24G\KFK[ RKFTFWGXHYJYLXNWOTP RKPTPWQXRYTYWXYWZT[K[
  503 19H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZV
  504 16G\KFK[ RKFRFUGWIXKYNYSXVWXUZR[K[
  505 12H[LFL[ RLFYF RLPTP RL[Y[
  506  9HZLFL[ RLFYF RLPTP
  507 23H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZVZS RUSZS
  508  9G]KFK[ RYFY[ RKPYP
  509  3NVRFR[
  510 11JZVFVVUYTZR[P[NZMYLVLT
  511  9G\KFK[ RYFKT RPOY[
  512  6HYLFL[ RL[X[
  513 12F^JFJ[ RJFR[ RZFR[ RZFZ[
  514  9G]KFK[ RKFY[ RYFY[
  515 22G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF
  516 14G\KFK[ RKFTFWGXHYJYMXOWPTQKQ
  517 25G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF RSWY]
  518 17G\KFK[ RKFTFWGXHYJYLXNWOTPKP RRPY[
  519 21H\YIWGTFPFMGKIKKLMMNOOUQWRXSYUYXWZT[P[MZKX
  520  6JZRFR[ RKFYF
  521 11G]KFKULXNZQ[S[VZXXYUYF
  522  6I[JFR[ RZFR[
  523 12F^HFM[ RRFM[ RRFW[ R\FW[
  524  6H\KFY[ RYFK[
  525  7I[JFRPR[ RZFRP
  526  9H\YFK[ RKFYF RK[Y[
""".strip('\n')
_uppercase_chars = [chr(x) for x in range(ord('A'), ord('Z') + 1)]
_uppercase_dict = dict(zip(_uppercase_chars, [line[6:] for line in _uppercase_data.split('\n')]))
_numbers_data = r"""
  700 18H\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF
  701  5H\NJPISFS[
  702 15H\LKLJMHNGPFTFVGWHXJXLWNUQK[Y[
  703 16H\MFXFRNUNWOXPYSYUXXVZS[P[MZLYKW
  704  7H\UFKTZT RUFU[
  705 18H\WFMFLOMNPMSMVNXPYSYUXXVZS[P[MZLYKW
  706 24H\XIWGTFRFOGMJLOLTMXOZR[S[VZXXYUYTXQVOSNRNOOMQLT
  707  6H\YFO[ RKFYF
  708 30H\PFMGLILKMMONSOVPXRYTYWXYWZT[P[MZLYKWKTLRNPQOUNWMXKXIWGTFPF
  709 24H\XMWPURRSQSNRLPKMKLLINGQFRFUGWIXMXRWWUZR[P[MZLX
""".strip('\n')
_number_chars = [str(x) for x in range(10)]
_numbers_dict = dict(zip(_number_chars, [line[6:] for line in _numbers_data.split('\n')]))
_misc = {
    '!': r'  714  9MWRFRT RRYQZR[SZRY',
    '?': r'  715 21I[LKLJMHNGPFTFVGWHXJXLWNVORQRT RRYQZR[SZRY',
    ' ': r'  699  1JZ',
    '"': r'  717  6JZNFNM RVFVM',
    '#': r'  733 12H]SBLb RYBRb RLOZO RKUYU',
    '$': r'  719 27H\PBP_ RTBT_ RYIWGTFPFMGKIKKLMMNOOUQWRXSYUYXWZT[P[MZKX',
    '&': r'  734 35E_\O\N[MZMYNXPVUTXRZP[L[JZIYHWHUISJRQNRMSKSIRGPFNGMIMKNNPQUXWZY[[[\Z\Y',
    "'": r'  731  8MWRHQGRFSGSIRKQL',
    '(': r'  721 11KYVBTDRGPKOPOTPYR]T`Vb',
    ')': r'  722 11KYNBPDRGTKUPUTTYR]P`Nb',
    ',': r'  711  9MWSZR[QZRYSZS\R^Q_',
    '-': r'  724  3E_IR[R',
    '.': r'  710  6MWRYQZR[SZRY',
    '/': r'  720  3G][BIb',
}
_misc = {k: v[6:] for k, v in _misc.items()}
CODE_FROM_CHAR = _uppercase_dict | _lowercase_dict | _numbers_dict | _misc
